# WLAN
WIFI_SSID = "ssid"
WIFI_PASSWORD = "pass"

# TM1637 Module
TM_CLK_PIN = 2
TM_DIO_PIN = 4

# Low Brightness hours
LOW_BRIGHTNESS_HOUR_FROM = 0
LOW_BRIGHTNESS_HOUR_TO = 8

# tm1637 Screen Brightness
TM_LOW_BRIGHTNESS_SETTING = 0
TM_HIGH_BRIGHTNESS_SETTING = 5

# ssd1306 Screen Brightness
SSD_LOW_BRIGHTNESS_SETTING = 0
SSD_HIGH_BRIGHTNESS_SETTING = 255