# WLAN
WIFI_SSID = "n2"
WIFI_PASSWORD = "n2n4n6n8"

# UTC Offset
UTC_OFFSET = "+3"

# TM1637 Module
TM_CLK_PIN = 2
TM_DIO_PIN = 4

# Clock Brightness
LOW_BRIGHTNESS_HOUR_FROM = 0
LOW_BRIGHTNESS_HOUR_TO = 8
LOW_BRIGHTNESS_SETTING = 0
HIGH_BRIGHTNESS_SETTING = 5